name: Aplicação Django

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALEVNS: 1
    runs-on: ubuntu-latest

  steps:
  - use: actions/checkout@v2
  - name: Set up Python 3.8
  with:
    python-version: 3.8
  - name: Instalar Dependências
    run:
    pip install pyenv
    sync pipenv --dev
  - name: Rodar Teste Automáticos
  run: |
    pipenv run pytest webdev

